/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import trabajo.practico.pkg6.Directorio;

/**
 *
 * @author giani
 */
public class Menu extends javax.swing.JFrame {

    Directorio d1=new Directorio();
    public Menu() {
        initComponents();
        this.setSize(800, 600);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        BAgregarCliente = new javax.swing.JButton();
        BBuscarCliente = new javax.swing.JButton();
        BBorrarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BAgregarCliente.setText("Agregar Cliente");
        BAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarClienteActionPerformed(evt);
            }
        });

        BBuscarCliente.setText("Buscar Cliente");
        BBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarClienteActionPerformed(evt);
            }
        });

        BBorrarCliente.setText("Borrar Cliente");
        BBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarClienteActionPerformed(evt);
            }
        });

        escritorio.setLayer(BAgregarCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(BBuscarCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(BBorrarCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BAgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBorrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBuscarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(BAgregarCliente)
                .addGap(18, 18, 18)
                .addComponent(BBuscarCliente)
                .addGap(18, 18, 18)
                .addComponent(BBorrarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarClienteActionPerformed
        javax.swing.JInternalFrame ventana=new JFAgregarCliente(d1);
        escritorio.add(ventana);
        ventana.setVisible(true);

    }//GEN-LAST:event_BAgregarClienteActionPerformed

    private void BBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarClienteActionPerformed
        javax.swing.JInternalFrame ventana=new JFBuscarCliente(d1);
        escritorio.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_BBuscarClienteActionPerformed

    private void BBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarClienteActionPerformed
        javax.swing.JInternalFrame ventana=new JFBorrarCliente(d1);
        escritorio.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_BBorrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregarCliente;
    private javax.swing.JButton BBorrarCliente;
    private javax.swing.JButton BBuscarCliente;
    private javax.swing.JDesktopPane escritorio;
    // End of variables declaration//GEN-END:variables
}
